### ISSUE TITLE
ReferenceError: _ff9‍ is not defined

### ISSUE THREAD

**Issue by mfolkeseth** [jhnns/rewire#158]
I'm getting this cryptic error on code which have previously been working just fine. Without any research results I thought maybe you guys have any idea what might be going on.

When I call `data.__set__('db', mock)` i get the following error ***ReferenceError: _ff9‍ is not defined***. 
The related file resides in `/node_modules/.cache/esm...`
Some info from the stacktrace

```
    not ok test/data_test.js
    timeout: 30000
    file: test/data_test.js
    childId: 0
    command: /usr/local/bin/node
    args:
      - '-r'
      - /Users/me/project/node_modules/esm/esm.js
      - test/data_test.js
    stdio:
      - 0
      - pipe
      - 2
    cwd: /Users/me/project
    exitCode: 1
```

Source
```
const tap = require('tap')
const rewire = require('rewire')
const data = rewire('../server/data')

const mock = {
  getSeries: async () => {
    return {}
  }
}
data.__set__('db', mock)
```

EDIT: esm is a tap dependency
EDIT: Issue occurs for tap version 12.5.0 or newer
